/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

#import "AppDelegate.h"
//Bugtags
#import <Bugtags/Bugtags.h>
//UMSocial
#import "UMSocial.h"
//EMSDK
#import "EMSDK.h"
//bridge
#import "EMSDKBridge.h"


#import "RCTRootView.h"


//Bugtags
#define BugtagsAppkey @"ae643ba5cf7dbbd0b6198afc60d3e264"
//EMSDKAppkey
#define EMSDKAppkey @"strawferry#umengrn"
//UMSocialAppkey
#define UMSocialAppkey @"5774ceede0f55a99f3000056"
//SinaAppkey
#define SinaAppkey @"1193338128"
//SinaSecret
#define SinaSecret @"8cdc41b62bd40823e68d14821d4e88db"
//SinaRedirectURL
#define SinaRedirectURL @"http://www.baidu.com"

//localhostURL
#define localhostURL @"localhost"
//@"10.19.49.215"



@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{

  [self initBugtags];//设置Bugtags
  //AppKey:注册的AppKey，详细见下面注释。
  //apnsCertName:推送证书名（不需要加后缀），详细见下面注释。
  EMOptions *options = [EMOptions optionsWithAppkey:EMSDKAppkey];
  options.apnsCertName = @"istore_dev";
  [[EMClient sharedClient] initializeSDKWithOptions:options];
  NSURL *jsCodeLocation;

  /**
   * Loading JavaScript code - uncomment the one you want.
   *
   * OPTION 1
   * Load from development server. Start the server from the repository root:
   *
   * $ npm start
   *
   * To run on device, change `localhost` to the IP address of your computer
   * (you can get this by typing `ifconfig` into the terminal and selecting the
   * `inet` value under `en0:`) and make sure your computer and iOS device are
   * on the same Wi-Fi network.
   */
  jsCodeLocation = [NSURL URLWithString:[NSString stringWithFormat:@"http://%@:8081/index.ios.bundle?platform=ios&dev=true",localhostURL]];
  

  /**
   * OPTION 2
   * Load from pre-bundled file on disk. The static bundle is automatically
   * generated by the "Bundle React Native code and images" build step when
   * running the project on an actual device or running the project on the
   * simulator in the "Release" build configuration.
   */
  

  
//   jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];

   RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"UMengRN"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  /**
   * OPTION 3
   * Load from pre-bundled file on disk. The static bundle is automatically
   * generated by the "Bundle React Native code and images" build step when
   * running the project on an actual device or running the project on the
   * simulator in the "Release" build configuration.
   */
//  self.bridge = [[RCTBridge alloc]initWithDelegate:self launchOptions:launchOptions];
//  AppDelegate *delegate = (AppDelegate *)[[UIApplication sharedApplication] delegate];
//  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:delegate.bridge moduleName:@"UMengRN" initialProperties:nil];
  
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

//
- (void)initBugtags{
  [Bugtags startWithAppKey:BugtagsAppkey invocationEvent:BTGInvocationEventBubble];
  BugtagsOptions *options = [[BugtagsOptions alloc] init];
  options.trackingUserSteps = YES; // 具体可设置的属性请查看 Bugtags.h
  [Bugtags setInvocationEvent:BTGInvocationEventShake];
  [Bugtags startWithAppKey:BugtagsAppkey invocationEvent:BTGInvocationEventBubble options:options];
}
- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge {
  return [NSURL URLWithString:[NSString stringWithFormat:@"http://%@:8081/index.ios.bundle?platform=ios&dev=true",localhostURL]];
}
// APP进入后台
- (void)applicationDidEnterBackground:(UIApplication *)application
{
  [[EMClient sharedClient] applicationDidEnterBackground:application];
}
// APP将要从后台返回
- (void)applicationWillEnterForeground:(UIApplication *)application
{
  [[EMClient sharedClient] applicationWillEnterForeground:application];
}


@end
